# Anibal Muñoz
# 21.087.122-5
# Diego Vergara
# 19.940.239-0
# Cristobal Galaz
# 20.359.833-5

In [22]:
#pip install pandas 
#pip install numpy
#pip install seaborn
#pip install kagglehub
#pip install -U scikit-learn
#pip install tensorflow
#pip install keras

In [2]:
#------Manejo de datos------
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import StandardScaler
#------Modelos------
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import ShuffleSplit
#------Reportes------
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_validate, StratifiedKFold

In [3]:
data_train = pd.read_excel("data_train.xlsx")
data_test = pd.read_excel("data_test.xlsx")

In [4]:
data_test = pd.DataFrame(data_test)
data_test.shape

(103284, 24)

In [6]:
data_train = pd.DataFrame(data_train)
data_train.shape

(25810, 24)

# Ya habiendo limpiado los 2 dataframes se procedera a aplicar modelos de clasificacion para predecir la satisfaccion de los clientes de la aerolinea

In [10]:
X_train = data_train.drop('satisfaction_encoded', axis=1)
y_train = data_train['satisfaction_encoded']
X_test = data_test.drop('satisfaction_encoded', axis=1)
y_test = data_test['satisfaction_encoded']

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(25810, 23)
(25810,)
(103284, 23)
(103284,)


In [12]:
# Inicializar StandardScaler
scaler = StandardScaler()

# Ajustar y transformar las características de entrenamiento
X_train_scaled = scaler.fit_transform(X_train)

# Transformar las características de prueba usando el mismo scaler ajustado en los datos de entrenamiento
X_test_scaled = scaler.transform(X_test)

# Ahora X_train_scaled y X_test_scaled contienen los datos escalados


REGRESION LOGISTICA , KNN , ARBOL DE DECISION, RANDOM FOREST,RED NEURONAL

In [66]:
# Reduce dataset size to 1%
# Esta seccion se hizo para probar con trozos del dataset, se los parametros estan para usarlo completo ahora
sample_size = int(len(X_train_scaled) * 1)
X_train_sampled = X_train.sample(n=sample_size, random_state=366)
y_train_sampled = y_train.loc[X_train_sampled.index]

sample_size = int(len(X_test_scaled) * 1)
X_test_sampled = X_test.sample(n=sample_size, random_state=366)
y_test_sampled = y_test.loc[X_test_sampled.index]



# Logistic Regression
logreg_model = LogisticRegression(max_iter=10000)
logreg_model.fit(X_train_sampled, y_train_sampled)
logreg_predictions = logreg_model.predict(X_test_sampled)
print("\nLogistic Regression Classification Report:")
print(classification_report(y_test_sampled, logreg_predictions))


# KNN
knn_model = KNeighborsClassifier()
knn_model.fit(X_train_sampled, y_train_sampled)
knn_predictions = knn_model.predict(X_test_sampled)
print("\nKNN Classification Report:")
print(classification_report(y_test_sampled, knn_predictions))


# Decision Tree
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train_sampled, y_train_sampled)
dt_predictions = dt_model.predict(X_test_sampled)
print("\nDecision Tree Classification Report:")
print(classification_report(y_test_sampled, dt_predictions))

# Random Forest
rf_model = RandomForestClassifier(random_state=366)  # Added random_state for reproducibility
rf_model.fit(X_train_sampled, y_train_sampled)
rf_predictions = rf_model.predict(X_test_sampled)
print("\nRandom Forest Classification Report:")
print(classification_report(y_test_sampled, rf_predictions))

# Red Neuronal
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical


rn_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])
    
rn_model.compile(optimizer='adam',
                loss='binary_crossentropy',
                metrics=['accuracy'])
rn_model.fit(X_train, y_train, epochs=100, batch_size=8, verbose=0)

y_pred_probs = rn_model.predict(X_test)
y_pred_classes = (y_pred_probs > 0.5).astype(int)

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Accuracy en test: {accuracy:.2f}")
print("\nRed Neuronal Report:")
print(classification_report(y_test_sampled, y_pred_classes))


#Lista de modelos

models = [ logreg_model, knn_model, dt_model, rf_model]
nombres = [ 'Logistic Regression', 'KNN', 'Decision Tree', 'Random Forest']


Logistic Regression Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.90      0.89     58528
           1       0.87      0.83      0.85     44756

    accuracy                           0.87    103284
   macro avg       0.87      0.87      0.87    103284
weighted avg       0.87      0.87      0.87    103284


KNN Classification Report:
              precision    recall  f1-score   support

           0       0.73      0.76      0.74     58528
           1       0.67      0.63      0.65     44756

    accuracy                           0.71    103284
   macro avg       0.70      0.70      0.70    103284
weighted avg       0.70      0.71      0.70    103284


Decision Tree Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.94      0.94     58528
           1       0.92      0.93      0.93     44756

    accuracy                           0.94    103284
   macro avg      

C:\Users\Alumno\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


3228/3228 ━━━━━━━━━━━━━━━━━━━━ 1s 393us/step
Accuracy en test: 0.93

RN Report:
              precision    recall  f1-score   support

           0       0.57      0.58      0.57     58528
           1       0.43      0.42      0.43     44756

    accuracy                           0.51    103284
   macro avg       0.50      0.50      0.50    103284
weighted avg       0.51      0.51      0.51    103284



# Se aplica una validacion cruzada (Cross-Validation) a cada modelos para verificar si existe sobreajuste

In [54]:
for i in range (len(models)):
  print("\n")
  print("-"*50)
  print("Modelo: ",nombres[i])
  scores = cross_val_score(models[i], X_train_sampled, y_train_sampled, cv=5)
  print(scores)
  print('El promedio es:', np.mean(scores))
  print('La desviacion estandar es:', np.std(scores) )



--------------------------------------------------
Modelo:  Logistic Regression
[0.87039907 0.86691205 0.87020535 0.87194886 0.86923673]
El promedio es: 0.8697404106935297
La desviacion estandar es: 0.0016601538384834302


--------------------------------------------------
Modelo:  KNN
[0.69837272 0.70515304 0.69972879 0.7006974  0.69275475]
El promedio es: 0.6993413405656722
La desviacion estandar es: 0.004002157770977676


--------------------------------------------------
Modelo:  Decision Tree
[0.92328555 0.93064704 0.93607129 0.93335916 0.93684618]
El promedio es: 0.9320418442464161
La desviacion estandar es: 0.004892272489008788


--------------------------------------------------
Modelo:  Random Forest
[0.9502131  0.94866331 0.95447501 0.9552499  0.96067416]
El promedio es: 0.953855094924448
La desviacion estandar es: 0.0042201468591058135


In [55]:
# Evaluación en test real
for i in range (len(models)):
  print("\n")
  print("-"*50)
  print("Modelo: ",nombres[i])
  y_test_pred = models[i].predict(X_test_sampled)
  test_accuracy = accuracy_score(y_test_sampled, y_test_pred)

# Evaluación en entrenamiento (si no la habías hecho aún)
  y_train_pred = models[i].predict(X_train_sampled)
  train_accuracy = accuracy_score(y_train_sampled, y_train_pred)

  print(f"Accuracy en entrenamiento: {train_accuracy:.3f}")
  print(f"Accuracy en test:         {test_accuracy:.3f}")



--------------------------------------------------
Modelo:  Logistic Regression
Accuracy en entrenamiento: 0.870
Accuracy en test:         0.873


--------------------------------------------------
Modelo:  KNN
Accuracy en entrenamiento: 0.806
Accuracy en test:         0.705


--------------------------------------------------
Modelo:  Decision Tree
Accuracy en entrenamiento: 1.000
Accuracy en test:         0.935


--------------------------------------------------
Modelo:  Random Forest
Accuracy en entrenamiento: 1.000
Accuracy en test:         0.954


In [57]:
# Definir las métricas que deseas
scoring = ['accuracy', 'f1_macro', 'precision_macro', 'recall_macro']

# Crear objeto StratifiedKFold con 5 folds
cv_strategy = StratifiedKFold(n_splits=5, shuffle=True, random_state=366)
for i in range (len(models)):
  print("\n")
  print("-"*50)
  print("Modelo: ",nombres[i])

# Ejecutar validación cruzada con StratifiedKFold
  cv_results = cross_validate(
      models[i],
      X_train_sampled,
      y_train_sampled,
      cv=cv_strategy,
      scoring=scoring,
      return_train_score=True
  )

# Imprimir resultados por métrica
  for metric in scoring:
      test_scores = cv_results[f'test_{metric}']
      train_scores = cv_results[f'train_{metric}']
      print(f"\n🔷 {metric.upper()}")
      print(f"Train promedio: {train_scores.mean():.3f}")
      print(f"Test promedio:  {test_scores.mean():.3f} ± {test_scores.std():.3f}")



--------------------------------------------------
Modelo:  Logistic Regression

🔷 ACCURACY
Train promedio: 0.870
Test promedio:  0.870 ± 0.003

🔷 F1_MACRO
Train promedio: 0.867
Test promedio:  0.867 ± 0.003

🔷 PRECISION_MACRO
Train promedio: 0.869
Test promedio:  0.869 ± 0.003

🔷 RECALL_MACRO
Train promedio: 0.866
Test promedio:  0.866 ± 0.004


--------------------------------------------------
Modelo:  KNN

🔷 ACCURACY
Train promedio: 0.800
Test promedio:  0.696 ± 0.007

🔷 F1_MACRO
Train promedio: 0.795
Test promedio:  0.689 ± 0.007

🔷 PRECISION_MACRO
Train promedio: 0.798
Test promedio:  0.691 ± 0.007

🔷 RECALL_MACRO
Train promedio: 0.793
Test promedio:  0.688 ± 0.007


--------------------------------------------------
Modelo:  Decision Tree

🔷 ACCURACY
Train promedio: 1.000
Test promedio:  0.932 ± 0.003

🔷 F1_MACRO
Train promedio: 1.000
Test promedio:  0.931 ± 0.003

🔷 PRECISION_MACRO
Train promedio: 1.000
Test promedio:  0.931 ± 0.003

🔷 RECALL_MACRO
Train promedio: 1.000
Test 

# Metodo KFold para Cross-Validation

In [94]:
#KFold
kf = KFold(n_splits=5, shuffle=True, random_state=366)

train_accuracies = []
val_accuracies = [] 

for train_index, val_index in kf.split(X_train):
    X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
    y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]
    model = Sequential([
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    model.fit(X_train_fold, y_train_fold, epochs=10, batch_size=32, verbose=0)
    # Evaluar el modelo en el conjunto de entrenamiento
    train_loss, train_accuracy = model.evaluate(X_train_fold, y_train_fold, verbose=0)
    train_accuracies.append(train_accuracy)
    # Evaluar el modelo en el conjunto de validación
    val_loss, val_accuracy = model.evaluate(X_val_fold, y_val_fold, verbose=0)
    val_accuracies.append(val_accuracy)

# Mostrar resultados
print("Precisión en entrenamiento por fold:", train_accuracies)
print("Precisión en validación por fold:", val_accuracies)

# Promedio y desviación estándar
print("Precisión media de entrenamiento:", np.mean(train_accuracies))
print("Precisión media de validación:", np.mean(val_accuracies))
print("Desviación estándar de la precisión de entrenamiento:", np.std(train_accuracies))
print("Desviación estándar de la precisión de validación:", np.std(val_accuracies))


C:\Users\Alumno\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Alumno\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Alumno\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwa

Precisión en entrenamiento por fold: [0.8624079823493958, 0.851123571395874, 0.8416311740875244, 0.857758641242981, 0.79286128282547]
Precisión en validación por fold: [0.8599380254745483, 0.8459899425506592, 0.8428903818130493, 0.8580007553100586, 0.7898101806640625]
Precisión media de entrenamiento: 0.8411565303802491
Precisión media de validación: 0.8393258571624755
Desviación estándar de la precisión de entrenamiento: 0.025136636312477416
Desviación estándar de la precisión de validación: 0.02562237847073867


# Metodo Shuffle Split para Cross-Validation

In [96]:
#Shuffle Split
ss = ShuffleSplit(n_splits=5, test_size=0.2, random_state=366)

train_accuracies = []
val_accuracies = []

for train_index, val_index in ss.split(X_train):
    X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
    y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]
    model = Sequential([
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(1, activation='sigmoid')
    ])
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    model.fit(X_train_fold, y_train_fold, epochs=10, batch_size=32, verbose=0)
    # Evaluar el modelo en el conjunto de entrenamiento
    train_loss, train_accuracy = model.evaluate(X_train_fold, y_train_fold, verbose=0)
    train_accuracies.append(train_accuracy)
    # Evaluar el modelo en el conjunto de validación
    val_loss, val_accuracy = model.evaluate(X_val_fold, y_val_fold, verbose=0)
    val_accuracies.append(val_accuracy)

# Mostrar resultados
print("Precisión en entrenamiento por split:", train_accuracies)
print("Precisión en validación por split:", val_accuracies)

# Promedio y desviación estándar
print("Precisión media de entrenamiento:", np.mean(train_accuracies))
print("Precisión media de validación:", np.mean(val_accuracies))
print("Desviación estándar de la precisión de entrenamiento:", np.std(train_accuracies))
print("Desviación estándar de la precisión de validación:", np.std(val_accuracies))

C:\Users\Alumno\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Alumno\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\Alumno\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwa

Precisión en entrenamiento por split: [0.8618268370628357, 0.8063734769821167, 0.8361584544181824, 0.8658949732780457, 0.8690429925918579]
Precisión en validación por split: [0.8626501560211182, 0.800464928150177, 0.8314606547355652, 0.8605191707611084, 0.8616815209388733]
Precisión media de entrenamiento: 0.8478593468666077
Precisión media de validación: 0.8433552861213685
Desviación estándar de la precisión de entrenamiento: 0.023778602704154543
Desviación estándar de la precisión de validación: 0.024428699865780727
